#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : unicode-xid
Version  : 0.1.0
Release  : 2
URL      : https://github.com/unicode-rs/unicode-xid/archive/v0.1.0.tar.gz
Source0  : https://github.com/unicode-rs/unicode-xid/archive/v0.1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 MIT
Requires: unicode-xid-data
BuildRequires : cargo
BuildRequires : rustc

%description
# unicode-xid
Determine if a `char` is a valid identifier for a parser and/or lexer according to
[Unicode Standard Annex #31](http://www.unicode.org/reports/tr31/) rules.

%package data
Summary: data components for the unicode-xid package.
Group: Data

%description data
data components for the unicode-xid package.


%prep
%setup -q -n unicode-xid-0.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
mkdir .cargo
echo "[source.crates-io]
replace-with = 'vendored-sources'
[source.vendored-sources]
directory = '/usr/share/rust/src'" > .cargo/config
echo '{"files":{},"package":""}' > .cargo-checksum.json
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cargo build --release

%install
cargo clean
install -d -p %{buildroot}/usr/share/rust/src/unicode-xid
cp -a . %{buildroot}/usr/share/rust/src/unicode-xid

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/rust/src/unicode-xid/.cargo-checksum.json
/usr/share/rust/src/unicode-xid/.cargo/config
/usr/share/rust/src/unicode-xid/.gitignore
/usr/share/rust/src/unicode-xid/.travis.yml
/usr/share/rust/src/unicode-xid/COPYRIGHT
/usr/share/rust/src/unicode-xid/Cargo.lock
/usr/share/rust/src/unicode-xid/Cargo.toml
/usr/share/rust/src/unicode-xid/LICENSE-APACHE
/usr/share/rust/src/unicode-xid/LICENSE-MIT
/usr/share/rust/src/unicode-xid/README.md
/usr/share/rust/src/unicode-xid/scripts/unicode.py
/usr/share/rust/src/unicode-xid/src/lib.rs
/usr/share/rust/src/unicode-xid/src/tables.rs
/usr/share/rust/src/unicode-xid/src/tests.rs
